[package]
name = "hexalyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe.workspace = true
rfd.workspace = true
intelhexlib.workspace = true

[package.metadata.bundle]
name = "hexalyzer"
identifier = "none"
icon = ["docs/icon.icns"]
version = "0.1.0"
copyright = "Copyright Â© 2026"